[Log] Print content in error log files in spawn action error message
We are seeing issues like https://snapengine-builder-2.sc-corp.net/jenkins/job/bazel-unit-test/6049/console where the real message doesn't got print out in the logs.

```
real error:
Error: /private/var/tmp/_bazel_jchen/26a6608cebb0ef5e1c9ff08eedd1ef74/execroot/__main__/components/discoverfeed/premium/premium-core/src/main/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [@android_mvn//:app_aifactory_bloops_analytics] /var/folders/89/gngzz1cn74n0yt9fxth8czhw0000gp/T/manifest_merge_tmp16810264379575934749/bazel-out/darwin-fastbuild/bin/external/android_mvn/_aar/app_aifactory_bloops_analytics/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="app.aifactory.analytics" to force usage
Warning:
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
Jun 25, 2020 11:49:12 AM com.google.devtools.build.android.ManifestMergerAction main
SEVERE: Error during merging manifests
com.google.devtools.build.android.AndroidManifestProcessor$ManifestProcessingException: Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [@android_mvn//:app_aifactory_bloops_analytics] /var/folders/89/gngzz1cn74n0yt9fxth8czhw0000gp/T/manifest_merge_tmp16810264379575934749/bazel-out/darwin-fastbuild/bin/external/android_mvn/_aar/app_aifactory_bloops_analytics/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="app.aifactory.analytics" to force usage
	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:186)
	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:217)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$5.call(ResourceProcessorBusyBox.java:91)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:212)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:175)
```

The reason is that, this error is logged inside a log file and is not passed in any stream. By default bazel doesn't check the content in the log file.
This PR updated the logic so the log file has the highest priority in defining the error message.

Upstream PR: https://github.com/bazelbuild/bazel/pull/11691